jobs:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "12"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      script: yarn electron:build --mac
      cache:
        yarn: true
        directories:
          - node_modules
          - $HOME/.cache/electron
          - $HOME/.cache/electron-builder
          - $HOME/.electron

    - os: windows
      language: node_js
      node_js: "12"
      script: yarn electron:build --win
      env:
        - YARN_GPG=no
      cache:
        yarn: true
        directories:
          - node_modules
          - '%USERPROFILE%\.electron'
